import React from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';

import Messages from '../Messages';
import Board from '../Board';
import Home from '../Home';
import Welcome from '../Welcome';
import Scoreboard from '../Scoreboard';
import { Header, Wrapper, MsgDiv, AlertMessage, GameWrapper } from '../../components';
import { updateOpponent, onWinUpdateScoreboard } from './state-functions';
import { updateGameId, confirmJoinNewGame } from '../../socket';

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      gameId: '', // id of game
      message: '', // welcome and warning messages presented to users, updated from Board once move is validated
      role: '', // either 'X' or 'O' first user is given X on start new game, second user is give 'O' when join game
      name: '', // sent back to App from welcome container
      opponent: 'TBD', // updated once user joins
      userWins: 0, //  can update when a user has been identified
      opponentWins: 0,
      chatMessages: [], // new messages from server are sent here
      msgBody: '', // as message is being typed this value changes
    };

    /*
      This function is called after the first user creates a new game
      Updates the gameId that was generated by server, message to user, and gives them their role
    */
    updateGameId((err, gameId) => {
      this.setState({
        gameId,
        message: `Send your game id to a friend to play. Your game id is: ${gameId}`,
        role: 'X',
      });
    });

    /*
    Is called after the second user joins a game. Is only activated for the second user, NOT the first user
    updates gameId, role, and opponent
    */
    confirmJoinNewGame((err, data) => {
      this.setState({
        gameId: data.gameId,
        role: 'O',
        opponent: data.opponent,
      });
    });

    this.onSignUpUpdateName = this.onSignUpUpdateName.bind(this);
    this.updateOpponent = this.updateOpponent.bind(this);
    this.onWinUpdateScoreboard = this.onWinUpdateScoreboard.bind(this);
    this.updateAlertMessage = this.updateAlertMessage.bind(this);
  }

  /*
    Takes in winner of game's role and upates scoreboard userWins is winner
    or opponentWins if other person is winner
    params: role of winner
  */
  onWinUpdateScoreboard(winner) {
    const newState = onWinUpdateScoreboard(this.state, winner);
    this.setState(newState);
  }
  /*
  params: name of player to sign up (from welcome page)
  returns: updates name in state
  */
  onSignUpUpdateName(name) {
    this.setState({ name });
  }

  /*
    Is called once 'startGame' action is emmited once second player joins game.
    Updates opponet for both (really only imported for player one)
    resets message to blank string
    params: array of the players in the game
  */
  updateOpponent(players) {
    // updateOpponent checks to see if name matches player and sets opponent to the opposite
    const opponent = updateOpponent(this.state.name, players);
    this.setState({ opponent, message: '' });
  }

  /*
  updates alert message if message is not valid or to set back to empty string after a valid play
  */
  updateAlertMessage(message) {
    this.setState({ message });
  }

  render() {
    return (
      <Wrapper>
        <Header>Tic-Tac-Toe</Header>
        <MsgDiv>
          <AlertMessage>{this.state.message}</AlertMessage>
        </MsgDiv>
        <Router>
          <Switch>
            <Route
              exact
              path="/"
              render={() => (
                <Wrapper>
                  <Welcome
                    updateName={this.onSignUpUpdateName}
                  />
                </Wrapper>
              )}
            />
            <Route
              path="/home"
              render={() => (
                <Wrapper>
                  <Home
                    name={this.state.name}
                    updateMessage={this.updateAlertMessage}
                  />
                </Wrapper>
              )}
            />
            <Route
              path="/game"
              render={() => (
                <GameWrapper>
                  <Wrapper>
                    <Board
                      message={this.state.message}
                      gameId={this.state.gameId}
                      updateOpponent={this.updateOpponent}
                      role={this.state.role}
                      name={this.state.name}
                      opponent={this.state.opponent}
                      updateScoreboard={this.onWinUpdateScoreboard}
                      updateMessage={this.updateAlertMessage}
                    />
                    <Scoreboard
                      name={this.state.name}
                      opponent={this.state.opponent}
                      userWins={this.state.userWins}
                      opponentWins={this.state.opponentWins}
                    />
                  </Wrapper>
                  <Messages
                    gameId={this.state.gameId}
                    name={this.state.name}
                  />
                </GameWrapper>
              )}
            />
          </Switch>
        </Router>
      </Wrapper>
    );
  }
}

export default App;
